server:
  port: 8090
  
#dubbo:
#  application:
#    name: user-service
#    
#  registry:
#    protocol: zookeeper
#    address: 127.0.0.1:2181
#    
#  protocol:
#    name: dubbo
##    port: 20881
#    
#  monitor:
#    protocol: registry